/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ItemType = IDL.Variant({
  'brainrotItem' : IDL.Text,
  'robloxAccount' : IDL.Record({
    'username' : IDL.Text,
    'level' : IDL.Nat,
    'inventoryHighlights' : IDL.Text,
  }),
});
export const ListingStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const Time = IDL.Int;
export const TradeListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'createdAt' : Time,
  'posterDisplayName' : IDL.Text,
  'requestedItem' : ItemType,
  'offeredItem' : ItemType,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'closeListing' : IDL.Func([IDL.Nat], [], []),
  'createListing' : IDL.Func([IDL.Text, ItemType, ItemType], [IDL.Nat], []),
  'getActiveListings' : IDL.Func([], [IDL.Vec(TradeListing)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(TradeListing)], ['query']),
  'getListingDetails' : IDL.Func([IDL.Nat], [TradeListing], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ItemType = IDL.Variant({
    'brainrotItem' : IDL.Text,
    'robloxAccount' : IDL.Record({
      'username' : IDL.Text,
      'level' : IDL.Nat,
      'inventoryHighlights' : IDL.Text,
    }),
  });
  const ListingStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const Time = IDL.Int;
  const TradeListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'createdAt' : Time,
    'posterDisplayName' : IDL.Text,
    'requestedItem' : ItemType,
    'offeredItem' : ItemType,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'closeListing' : IDL.Func([IDL.Nat], [], []),
    'createListing' : IDL.Func([IDL.Text, ItemType, ItemType], [IDL.Nat], []),
    'getActiveListings' : IDL.Func([], [IDL.Vec(TradeListing)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(TradeListing)], ['query']),
    'getListingDetails' : IDL.Func([IDL.Nat], [TradeListing], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };